[package]
name        = "dirs-sys-next"
version     = "0.1.2"
authors     = ["The @xdg-rs members"]
description = "system-level helper functions for the dirs and directories crates"
edition     = "2018"
readme      = "README.md"
license     = "MIT OR Apache-2.0"
repository  = "https://github.com/xdg-rs/dirs/tree/master/dirs-sys"
include = [
    '/CHANGELOG.md',
    '/Cargo.toml',
    '/LICENSE-*',
    '/README.md',
    '/src',
]

[badges]
maintenance = { status = "as-is" }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "redox")'.dependencies]
redox_users = { version = "0.4.0", default-features = false }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.45.0", features = [
    "Win32_UI_Shell",
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_System_Com",
] }
