status = [
  "build (ubuntu-latest, stable)",
  "build (windows-latest, stable)",
  "build (macos-latest, stable)",
  "build (ubuntu-latest, 1%)",
  "build (windows-latest, 1%)",
  "build (macos-latest, 1%)",
]

# Default timeout is one hour
timeout_sec = 600
